// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aazdegzpodvfnsbrjyro.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFhemRlZ3pwb2R2Zm5zYnJqeXJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5Nzk2MTMsImV4cCI6MjA2NTU1NTYxM30.DORwkYHYDzFSjEl05e8Rg5nK7JrTKazQX6XZaxkMvms";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);